# Generated by Django 3.1.3 on 2021-02-27 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ModelB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('a_ptr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_app.modela')),
            ],
        ),
        migrations.AddConstraint(
            model_name='modelb',
            constraint=models.UniqueConstraint(fields=('a_ptr', 'x'), name='demo_app_modelb_unique_a_ptr_x'),
        ),
    ]
