# Generated by Django 3.1.3 on 2021-02-27 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='modelb',
            name='demo_app_modelb_unique_a_ptr_x',
        ),
    ]
